import 'models/model_astuces_conseils.dart';

const DATA_ASTUCE_CONSEILS = [
  AstucesConseilsModel(
      id: '1',
      titre: 'Pour un usage sur et responsable d’internet',
      imageUrl: 'assets/astuce_POUR_UN_USAGE_SUR_RESPONSABLE_INTERNET.jpg',
      description:
          "Le spam peut être entendu comme l’envoi massif et parfois répété de courriers électroniques non sollicités, le plus souvent à caractère commercial, à des personnes avec lesquelles l’expéditeur n’a jamais eu de contact et dont il a capté l’adresse électronique dans les espaces publics de l’internet : forums de discussion, listes de diffusion, annuaires, sites Web, etc. Le phishing (hameçonnage ou filoutage) est une technique par laquelle des personnes malveillantes se font passer pour de grandes sociétés ou des organismes financiers qui vous sont familiers en envoyant des mèls frauduleux et récupèrent des mots de passe de comptes bancaires ou numéros de cartes de crédit pour détourner des fonds."),
  AstucesConseilsModel(
    id: '2',
    titre:
        'Comment protéger les données personnelles des clients dans le cadre du e-commerce.',
    imageUrl:
        'assets/astuce_comment_proteger_les_donnes_personnelles_des_clients_dans_le_cadre_du_ecommerce.jpg',
    description:
        "Le commerce électronique ou vente en ligne désigne l’échange de biens et de services entre deux entités sur le réseau internet ou via les réseaux téléphoniques mobiles. L’essor de l’internet et du commerce électronique ont créé des menaces sans précédent pour le respect de la vie privée du client consommateur. En effet, les sites de vente en ligne sont souvent très imprudents quant à la protection des données personnelles des consommateurs dans la mesure où ils minimisent les risques de vol ou d’utilisation frauduleuse des données personnelles : usurpation, fraude à la carte bancaire, etc. Le respect des obligations légales en matière de données personnelles sur leurs ventes peut avoir un impact positif pour les sites e-commerce. Afin de gagner la confiance des clients et de satisfaire aux exigences légales, une entreprise exploitant un site de e-commerce doit appliquer une politique stricte de protection des données personnelles. A cet effet, elle doit : traiter les données récoltées sur ses clients de manière transparente, sécurisée et confidentielle ; respecter les formalités déclaratives auprès de la CDP et en vérifiant que les questionnaires de collecte sont conforme à la règlementation; utiliser des techniques d’authentification de l’utilisateur et de cryptage des données personnelles ; demander uniquement aux clients des informations indispensables ; indiquer clairement quelles données personnelles sont exploitées et à quelle fin ; donner à l’utilisateur le droit de limiter l’usage qui est fait de ses données et leur transmission (profil de consommation, publicité) ; tester régulièrement les vulnérabilités de leur système d’information pour éviter le piratage des données personnelles ; afficher une politique de vie privée expliquant sa ligne de conduite en ce qui concerne cette information sur la page d’accueil du site ; limiter la saisie des mots de passe pour ne pas donner la possibilité aux pirates d’en tester beaucoup aux fins de trouver le bon ; faciliter le droit d’accès, d’opposition et de rectification des clients; informer les clients personnes concernées avant la cession de leurs données personnelles à un partenaire commercial ; éviter de conserver les données collectées au-delà de la ou les finalités déclarées ; respecter les conditions de la prospection directe conformément à la Délibération N°2014-20/CDP du 30 mai 2014. En application des articles 29 et 30 de la loi sur les données à caractère personnel, des sanctions administratives, pécuniaires et pénales peuvent être prononcées, soit par la CDP ou par les juridictions compétentes à l’égard de tout responsable de traitement n’ayant pas respecté ses obligations.",
  ),
  AstucesConseilsModel(
    id: '3',
    titre: 'Comment réagir face au Cyber harcèlement',
    imageUrl: 'assets/astuce_comment_reagir_face_au_Cyber_harcelement.jpg',
    description:
        "Le cyber harcèlement est une forme de harcèlement conduite par divers canaux numériques. Elle se présente sous divers aspects :le fait d’utiliser les technologies d’information et de la communication pour porter délibérément atteinte à un individu, de manière répétée dans le temps ; forme d’agression qui se caractérise par la réception non désirée et répétée de messages par SMS ou sur l’internet (MSN, e-mail, réseaux sociaux.) Le cyber harcèlement en ligne peut se manifester par l’humiliation, les moqueries, les injures, la diffamation, le discrédit, l’intimidation, l’usurpation d’identité, les menaces physiques, les prises de contact insistantes… Face à l’ampleur du phénomène du cyber harcèlement et ces conséquences néfastes sur la vie privée des personnes concernées, comment réagir ? Pour faire face à cette nouvelle forme d’harcèlement, il est fondamental pour les internautes : de protéger leurs données personnelles tout en assurant par exemple la confidentialité de son mot de passe et sa non divulgation à un tiers. de gérer ses paramètres de confidentialité lorsqu’on utilise les réseaux sociaux ; de réfléchir avant de publier un contenu sur site web ou un réseau social : Par ailleurs, toute personne concernée qui a été victime de cybercriminalité doit : recueillir les preuves : sauvegarder tous les messages reçus ; signaler les abus : signalement d’un ou des individus malveillants au responsable du site pour bloquer les profils ou comptes des agresseurs exercer son droit d’opposition auprès des responsables de ces sites concernés pour obtenir la suppression du contenu mis en cause. saisir la Commission de Protection des Données Personnelles (CDP) si vous n’obtenez pas gain de cause auprès du responsable de traitement; Poursuivre pénalement les auteurs des infractions correspondant au cyberharcèlement.",
  ),
];
